### ISSUE TITLE
Operator panics if PlacementAPI resource is created but KeystoneAPI is not available

### ISSUE THREAD

**Issue by gibizer** [openstack-k8s-operators/placement-operator#12]
### Steps to reproduce in crc:

-  deploy mariadb and the keystone operator but do not create KeystoneAPI resource: ``$ make mariadb mariadb_deploy keystone``
-  deploy placement operator: ``$ make placement``
-  watch the operator logs to observe the error: ``$oc logs --follow $(oc get pod | grep placement-operator-controller-manager | cut -d ' ' -f1)``
- try to create a PlacementAPI resource: ``$ make placement_deploy``

### Expected behavior:
The operator waits for the KeystoneAPI to become available

### Actual behavior:
The operator code panics.

### Logs:
```
1.656943723711964e+09	INFO	controllers.PlacementAPI	Reconciling Service
panic: runtime error: index out of range [0] with length 0

goroutine 514 [running]:
github.com/openstack-k8s-operators/keystone-operator/pkg/external.GetKeystoneAPI({0x1ac0778, 0xc00045e780}, 0xc0003185a0, {0xc001efcad0, 0x9}, 0xc00087cb40)
	/go/pkg/mod/github.com/openstack-k8s-operators/keystone-operator@v0.0.0-20220627061212-1cb72024240c/pkg/external/funcs.go:57 +0x1fa
github.com/openstack-k8s-operators/placement-operator/controllers.(*PlacementAPIReconciler).generateServiceConfigMaps(0x1682e80, {0x1ac0778, 0xc00045e780}, 0xa, 0xc0004e8200, 0xa)
	/remote-source/controllers/placementapi_controller.go:500 +0x2ac
github.com/openstack-k8s-operators/placement-operator/controllers.(*PlacementAPIReconciler).reconcileNormal(0xc0003dfb80, {0x1ac0778, 0xc00045e780}, 0xc0004e8200, 0xc0004e8200)
	/remote-source/controllers/placementapi_controller.go:403 +0x43a
github.com/openstack-k8s-operators/placement-operator/controllers.(*PlacementAPIReconciler).Reconcile(0xc0003dfb80, {0x1ac0778, 0xc00045e780}, {{{0xc000922860, 0x17d55a0}, {0xc000922856, 0x30}}})
	/remote-source/controllers/placementapi_controller.go:155 +0x316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0006f0000, {0x1ac0778, 0xc00045e540}, {{{0xc000922860, 0x17d55a0}, {0xc000922856, 0x413a94}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0006f0000, {0x1ac06d0, 0xc0003de080}, {0x1707b00, 0xc000be6080})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0006f0000, {0x1ac06d0, 0xc0003de080})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x357
```

**Comment by gibizer** [comment]
This is due to the fact that the GetKeystoneAPI helper from the Keystone operator assumes that there is always at least one KeystoneAPI resource is available: https://github.com/openstack-k8s-operators/keystone-operator/blob/85705ca340e4034477a7da394b03959e50b597ce/pkg/external/funcs.go#L71

**Comment by stuggi** [comment]
have you tested it with https://github.com/openstack-k8s-operators/keystone-operator/commit/defceb606c521f04f4f6935c0ee448a89b76eb4c ?
